---
abstract: 'Namespace manipulation and prefix mapping for XML, RDF, etc.'
author:
  - 'Chris Prather <chris@prather.org>'
  - 'Dorian Taylor <dorian@cpan.org>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: URI::NamespaceMap
name: URI-NamespaceMap
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 0
  URI: 1.52
  perl: 5.005
resources:
  bugtracker: https://github.com/kjetilk/URI-NamespaceMap/issues
  license: http://dev.perl.org/licenses/
version: 0.06
