---
abstract: 'Namespace manipulation and prefix mapping for XML, RDF, etc.'
author:
  - 'Chris Prather <chris@prather.org>'
  - 'Dorian Taylor <dorian@cpan.org>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.12'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: URI::NamespaceMap
name: URI-NamespaceMap
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  RDF::NS: 20130802
  RDF::Prefixes: 0
  XML::CommonNS: 0
requires:
  Carp: 0
  IRI: 0.004
  Module::Load::Conditional: 0
  Moose: 0
  Try::Tiny: 0
  Types::URI: 0.004
  URI: 1.52
  perl: 5.6.0
resources:
  bugtracker: https://github.com/kjetilk/URI-NamespaceMap/issues
  homepage: https://metacpan.org/module/URI::NamespaceMap
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kjetilk/URI-NamespaceMap/
version: 0.11_2
x_contributors:
  - 'Dorian Taylor <dorian@cpan.org>'
